---
- name: Install Minikube on various Linux distros
  hosts: localhost
  become: true
  vars_files:
    - vars.yml  # Vault vars containing user_password and other sensitive data

  tasks:
    - name: Gather OS information
      ansible.builtin.setup:
        gather_subset:
          - 'distribution'
      register: os_info

    - name: Remove conflicting containerd package (if exists)
      package:
        name: containerd.io
        state: absent
      ignore_errors: true

    - name: Ensure package cache is updated
      package:
        update_cache: yes

    - name: Add Docker repository for Ubuntu
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: os_info.ansible_facts['ansible_distribution'] == 'Ubuntu'

    - name: Add Docker repository for RedHat/CentOS
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        gpgcheck: yes
        enabled: yes
      when: os_info.ansible_facts['ansible_distribution'] in ['RedHat', 'CentOS']

    - name: Install dependencies for Minikube (all distros)
      package:
        name:
          - curl
          - ca-certificates
          - conntrack
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: os_info.ansible_facts['ansible_distribution'] in ['Ubuntu', 'RedHat', 'CentOS', 'SLES']

    - name: Install dependencies for Minikube (SLES)
      package:
        name:
          - curl
          - ca-certificates
          - conntrack
          - docker
        state: present
      when: os_info.ansible_facts['ansible_distribution'] == 'SLES'

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create a new user for Minikube
      user:
        name: minikube_user
        password: "{{ user_password }}"
        shell: /bin/bash

    - name: Add new user to docker group
      user:
        name: minikube_user
        groups: docker
        append: yes

    - name: Download kubectl binary version
      command: curl -L -s https://dl.k8s.io/release/stable.txt
      register: kubectl_version

    - name: Download and install kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Download Minikube binary
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Start Minikube as non-root user
      become_user: minikube_user
      command: minikube start --driver=docker
      register: minikube_start_output

    - debug:
        msg: "{{ minikube_start_output.stdout }}"
